name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
          retention-days: 1

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.REPO_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: target/*.jar